### ISSUE TITLE
关于static中的js

### ISSUE THREAD

**Issue by ruguoaaa** [NoisyWinds/laravel-smartmd#1]
你好，能不能把static中的js源代码也开源呢？

**Comment by NoisyWinds** [comment]
您好，感谢关注这个项目。
我准备分两个仓库，smartmd-editor 和 Laravel-smartmd
前端的项目还在准备当中，此项目是先行版。
预计在这个月底之前会有个初版。
我尽量..

**Comment by NoisyWinds** [comment]
> 你好，能不能把static中的js源代码也开源呢？

您好，感谢关注这个项目。
我准备分两个仓库，smartmd-editor 和 Laravel-smartmd
前端的项目还在准备当中，此项目是先行版。
预计在这个月底之前会有个初版。
我尽量..

**Comment by ruguoaaa** [comment]
### 辛苦辛苦
